name: Tagged Release Workflow
permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  check-valid-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check Valid Branch
        run: |
          branches=$(git branch -r --contains tags/${{ github.ref_name }})
          for branch in $branches; do
            if [[ $branch == "origin/master" ]]; then
              return 0;
            else
              return 1;
            fi
          done

  create-release:
    needs: [ check-valid-branch ]
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      
      matrix:
        target: [ win, linux ]
        architecture: [ x64, x86 ]
        compiler: [ mingw64, gcc ]
        build-type: [ release ]
        exclude:
          - target: windows
            compiler: gcc
          - target: linux
            compiler: mingw64

    steps:
      - name: Create Release
        uses: VolcanusLucis/.github/.github/actions/create-release@master
        with:
          tag: ${{ github.ref_name }}
          draft: 'true'

      - name: Build
        uses: VolcanusLucis/.github/.github/actions/build-cmake-project-presets@master
        with:
          target: ${{ matrix.target }}
          architecture: ${{ matrix.architecture }}
          compiler: ${{ matrix.compiler }}
          build-type: ${{ matrix.build-type }}

      - name: Install
        if: success()
        shell: bash
        run: |
          echo "folder=${{ matrix.target }}-${{ matrix.architecture }}-${{ matrix.compiler }}" >> $GITHUB_ENV
          cmake --install "build/${{ env.folder }}" --prefix "install/${{ env.folder }}" --config ${{ matrix.build-type }}

      - name: Package
        shell: bash
        run: |
          tar -C install/ -czf libvlmath-${{ env.folder }}.tar.gz ${{ env.folder }}

      - name: Upload
        uses: VolcanusLucis/.github/.github/actions/upload-to-release@master
        with:
          tag: ${{ github.ref_name }}
          file: 'libvlmath-${{ env.folder }}.tar.gz'